name: Coverage Report

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov coverage

      - name: Run tests and generate coverage
        run: |
          # coverage run -m pytest
          pytest -s --cov=mymodule
          ls -la
          coverage xml

      - name: Report coverage
        uses: insightsengineering/coverage-action@v2
        with:
          path: coverage.xml
          publish: true
          diff: true
          diff-branch: main
          diff-storage: _xml_coverage_reports
          coverage-summary-title: "Code Coverage Summary"
          coverage-reduction-failure: false
          new-uncovered-statements-failure: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
