name: Coverage Report

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
      - 'release/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov coverage

      - name: Run tests and generate coverage
        run: |
          PYTHONPATH=. pytest -s --cov=mymodule
          coverage xml

      - name: Set coverage path
        run: |
          if [[ "${{ github.head_ref || github.ref_name }}" == "main" ]]; then
            echo "COVERAGE_PATH=coverage/coverage.xml" | tee -a $GITHUB_ENV
          elif [[ "${{ github.head_ref || github.ref_name }}" == release/* ]]; then
            echo "COVERAGE_PATH=${GITHUB_REF_NAME}/coverage/coverage.xml" | tee -a $GITHUB_ENV
          fi

      - name: Report coverage
        uses: insightsengineering/coverage-action@v2
        with:
          path: ${{ env.COVERAGE_PATH }}
          publish: true
          threshold: 95
          diff: true
          diff-branch: main
          diff-storage: gh-pages
          # before-push-command: |
          #  mkdir -p "$(dirname "$COVERAGE_PATH")"
          #  mv coverage.xml "$COVERAGE_PATH"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERAGE_PATH: ${{ env.COVERAGE_PATH }}
