name: Coverage Report

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
      - 'release/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov coverage

      - name: Run tests and generate coverage
        run: |
          PYTHONPATH=. pytest -s --cov=mymodule
          coverage xml

      - name: Set coverage path
        id: set-path
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          if [[ "$BRANCH_NAME" == "main" ]]; then
            echo "coverage_path=coverage/coverage.xml" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == release/* ]]; then
            echo "coverage_path=$BRANCH_NAME/coverage/coverage.xml" >> $GITHUB_ENV
          fi

      - name: Report coverage
        uses: insightsengineering/coverage-action@v2
        with:
          path: ${{ env.coverage_path }}
          publish: true
          threshold: 95
          diff: true
          diff-branch: main
          diff-storage: gh-pages
          before-push-command: |
            mkdir -p "$(dirname "${{ env.coverage_path }}")"
            mv coverage.xml "${{ env.coverage_path }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
