name: test debugger with ngrok
on: workflow_dispatch

jobs:
  example_1:
    runs-on: ubuntu-latest
    steps:
      - name: create cluster
        uses: helm/kind-action@v1
      - name: uses debugger
        uses: shaowenchen/debugger-action@v2
        timeout-minutes: 30
        continue-on-error: true
        with:
          ngrok_token: ${{ secrets.NGROK_TOKEN }}
          ngrok_addr_1: 30000
          ngrok_proto_1: http
