name: Python API Tests

on:
#   push:
#     branches:
#       - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests pytest-html

    - name: Run tests with html output
      run: |
        pytest tests/test_api_httpbin.py -v \
            --self-contained-html \
            --html=reports/apitest_report.html
      continue-on-error: true

    - name: Checkout gh-pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: gh-pages

    - name: Copy report to gh-pages branch
      run: |
        mkdir -p gh-pages/apitest
        cp reports/apitest_report.html gh-pages/apitest/

    - name: Commit and push report to gh-pages
      run: |
        cd gh-pages
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@users.noreply.github.com'
        git add apitest/apitest_report.html
        git commit -m "Update API test report"
        git push origin gh-pages